# Generated by Django 4.0.6 on 2022-08-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_number', models.IntegerField()),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_password', models.CharField(max_length=100)),
            ],
        ),
    ]
