# Generated by Django 4.0.6 on 2022-07-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregateapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
