# Generated by Django 4.0.6 on 2022-08-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregateapp', '0002_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
